### ISSUE TITLE
scheme update?

### ISSUE THREAD

**Issue by l0rdicon** [Ballrock/node-csgo-parser#3]
I'm attempting to parse the csgo item list into a db but I'm having trouble getting this to work. 

It seems like the schema steam is giving back is different now. 

for example:

previous schema (in test data) 
`"result"
{
    "status"    "1"`

new schema 
`{
    "result": {`

**Comment by Ballrock** [comment]
Hi @l0rdicon,

Unless I'm mistaken, your "new schema" seems to be in JSON, node-csgo-parser only use VDF format for parsing.
You can find those by calling the STEAM API with `&format=vdf`.

Despite this, i must confess that node-csgo-parser need an health check-up....
